### ISSUE TITLE
SQL 2 not showing up in last exercise

### ISSUE THREAD

**Issue by ismayc** [datacamp/courses-intro-to-sql#122]
@yashasroy It looks like Joining Data with PostgreSQL isn't showing up in the [last exercise](https://campus.datacamp.com/courses/intro-to-sql-for-data-science/sorting-grouping-and-joins?ex=12), even though the [.md](https://github.com/datacamp/courses-intro-to-sql/edit/master/chapter4.md) file was changed. Does it need a manual rebuild?

![screen shot 2018-04-27 at 8 18 57 pm](https://user-images.githubusercontent.com/9215614/39378332-5cf2b3c0-4a58-11e8-8087-1e191f3bbf5b.png)

**Comment by yashasroy** [comment]
@ismayc It seems like builds in this course haven't been passing in this course because of a `sqlwhat` issue:

![screenshot 2018-04-27 14 49 44](https://user-images.githubusercontent.com/20912644/39379816-7a369efc-4a2a-11e8-87b4-da46d10cee0f.png)

Worrying, but at least the exercises in question run fine. What this means is that the last few commits to `master` are not live. I'll bring this to Filip's attention - CDs will need `sqlwhat` training in the coming months. 

Btw, you're now admin on all SQL courses.

**Comment by ismayc** [comment]
@yashasroy Thanks much. I think I should also be a part of `sqlwhat` training to better help with handoffs. Can you add me in whenever those get going?

**Comment by ismayc** [comment]
Appears to be working now.
